# Generated by Django 3.2.7 on 2021-12-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0002_auto_20211221_2335'),
        ('Vehiculos', '0002_alter_vehiculo_año'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nombre_repuesto', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(choices=[('O', 'Original'), ('A', 'Alterno')], default='O', max_length=1)),
                ('Fk_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedores')),
                ('Fk_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehiculos.vehiculo')),
            ],
        ),
    ]
