# Generated by Django 3.2.7 on 2021-12-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='valor',
        ),
    ]
