# Generated by Django 3.2.7 on 2021-12-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0002_remove_repuesto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='Costo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
