# Generated by Django 3.2.7 on 2021-12-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0003_repuesto_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='Costo',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
    ]
