# Generated by Django 3.2.7 on 2021-12-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0004_alter_repuesto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Repuestos'),
        ),
    ]
