# Generated by Django 3.2.7 on 2021-12-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0006_repuesto_garantia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='Descripcion',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='nombre_repuesto',
            new_name='Nombre_repuesto',
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='Costo',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='Fk_proveedor',
            new_name='Proveedor',
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='Fk_vehiculo',
            new_name='Vehiculo',
        ),
    ]
