# Generated by Django 3.2.7 on 2021-12-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.SlugField(max_length=4),
        ),
    ]
