# Generated by Django 3.2.7 on 2021-12-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0002_alter_vehiculo_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.CharField(max_length=4),
        ),
    ]
